# Site settings
title: Coding Vibes
header-img: img/home-bg.png
email: gnappo.1@live.it
copyright_name: gnappo1
description: > # this means to ignore newlines until "baseurl:"
  Inside the emotional roller coaster of my coding experience
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gnappo1
learn_profile: gnappo1
email_username: gnappo.1@live.it

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
